#!/usr/bin/env python3
"""
Build the two paper tables the harness does not emit on its own.

`run_report_eval` writes one table per run directory. E5 compares two runs
(learned pairing against heuristic pairing) and so spans two directories, and
E7's scene results ship as JSON without a LaTeX writer. Both are assembled
here, from the JSON, so no number in the paper is typed by hand.

    python paper/make_tables.py

Writes paper/tables/e5_pairing.tex and paper/tables/e7_scene.tex. Missing
inputs are reported and skipped rather than faked, so running this before the
full-scale runs land leaves the earlier table in place and says which one it
could not rebuild.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "tables"

# E5: same grounding, pairing swapped. Order puts ours last so the table's
# emphasis falls where the argument does.
E5_RUNS = [
    ("production heuristic", "results/levir_cc_caption_heuristic_pairing",
     "results/e5_heuristic_pairing"),
    ("learned head (ours)", "results/levir_cc_caption",
     "results/e5_learned_pairing"),
]
E5_MODE = "llm_graphrag"

E7_RUN = ["results/levir_cc_scene", "results/pilot_cc_scenes8/scene_level"]
E7_ORDER = ["template", "llm_struct", "llm_flat_rag", "llm_graphrag"]
E7_LABELS = {"template": "template (no LLM)", "llm_struct": "full concatenation",
             "llm_flat_rag": "top-$k$ retrieval", "llm_graphrag": "graph aggregate"}


def _first_existing(*rels: str) -> Path | None:
    for rel in rels:
        if rel and (ROOT / rel).is_dir():
            return ROOT / rel
    return None


def _rows(path: Path, name: str) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {r["name"]: r for r in payload.get("results", [])}, payload


def _pct(v) -> str:
    return "--" if v is None else f"{v * 100:.2f}"


def build_e5() -> str | None:
    rows, provenance = [], []
    for label, preferred, fallback in E5_RUNS:
        run = _first_existing(preferred, fallback)
        if run is None:
            print(f"  E5: no run directory for {label!r} "
                  f"(looked for {preferred}, {fallback})")
            return None
        by_mode, payload = _rows(run / "report_results_caption.json", label)
        if E5_MODE not in by_mode:
            print(f"  E5: {run} has no {E5_MODE} row")
            return None
        rows.append((label, by_mode[E5_MODE]))
        provenance.append(f"{label}: {run.relative_to(ROOT)} "
                          f"(n={payload.get('n_pairs')}, "
                          f"checkpoint={payload.get('checkpoint')})")

    n = {r.get("n_generated") for _, r in rows}
    lines = [
        "% generated by paper/make_tables.py -- do not edit",
        *[f"% {p}" for p in provenance],
        "\\begin{table}[t]", "\\centering",
        "\\caption{Report factuality with grounding held fixed at "
        "\\texttt{llm\\_graphrag} and only the pairing swapped (E5). "
        "Identical crops, style examples and language model.}",
        "\\label{tab:e5_pairing}",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lccccc}", "\\toprule",
        "Pairing & CFS-P & CFS-R & CFS-F1 & Hal & ChgAcc \\\\", "\\midrule",
    ]
    for i, (label, r) in enumerate(rows):
        cells = [_pct(r.get(k)) for k in ("cfs_precision", "cfs_recall", "cfs_f1",
                                          "hallucination_rate", "change_accuracy")]
        if i == len(rows) - 1:
            label = f"\\textbf{{{label}}}"
            cells = [f"\\textbf{{{c}}}" for c in cells]
        lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    if len(n) > 1:
        print(f"  E5: WARNING the two arms generated different counts: {n}")
    return "\n".join(lines)


def build_e7() -> str | None:
    run = _first_existing(*E7_RUN)
    if run is None:
        print(f"  E7: no run directory (looked for {', '.join(E7_RUN)})")
        return None
    payload = json.loads((run / "scene_results.json").read_text(encoding="utf-8"))
    by_name = {r["name"]: r for r in payload.get("results", [])}
    n_scenes = payload.get("n_scenes")
    gt = payload.get("gt_instances_per_scene") or {}
    mean_gt = sum(gt.values()) / len(gt) if gt else None

    # A tile is cut into 16 crops, but the test split does not carry all 16 for
    # every tile -- many scenes contribute one. Saying "all 16" would overstate
    # what the conditions were given, and on a single-crop scene the three
    # representations are trivially identical, so the spread is worth printing.
    cps = payload.get("crops_per_scene") or {}
    caption = ("Neighbourhood-level grounding (E7): one report per "
               "neighbourhood, over every crop of a tile the split provides. "
               "The conditions are three representations of the same "
               "observations, not an additive ladder.")
    if n_scenes is not None:
        caption += f" $n={n_scenes}$"
        if cps:
            vals = sorted(cps.values())
            multi = sum(1 for v in vals if v > 1)
            caption += (f", {min(vals)}--{max(vals)} crops each "
                        f"(mean {sum(vals) / len(vals):.1f}; {multi} scenes "
                        f"with more than one crop)")
        if mean_gt is not None:
            caption += f", mean {mean_gt:.1f} ground-truth instances per scene"
        caption += "."

    lines = [
        "% generated by paper/make_tables.py -- do not edit",
        f"% source: {run.relative_to(ROOT)} "
        f"(checkpoint={payload.get('checkpoint')})",
        "\\begin{table}[t]", "\\centering",
        f"\\caption{{{caption}}}",
        "\\label{tab:e7_scene}",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lccc}", "\\toprule",
        "Representation & CFS-F1 & Hal & scene CountMAE \\\\", "\\midrule",
    ]
    for name in E7_ORDER:
        r = by_name.get(name)
        if r is None:
            continue
        mae = r.get("scene_count_mae")
        lines.append(f"{E7_LABELS.get(name, name)} & {_pct(r.get('cfs_f1'))} & "
                     f"{_pct(r.get('hallucination_rate'))} & "
                     f"{'--' if mae is None else f'{mae:.2f}'} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    if payload.get("checkpoint") in (None, "None"):
        print("  E7: WARNING this run records no checkpoint -- it predates "
              "pairing_head.pt and its rows describe the pilot head")
    return "\n".join(lines)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    built, skipped = [], []
    for name, fn in (("e5_pairing", build_e5), ("e7_scene", build_e7)):
        print(f"{name}:")
        text = fn()
        if text is None:
            skipped.append(name)
            continue
        (OUT / f"{name}.tex").write_text(text + "\n", encoding="utf-8")
        print(f"  wrote {(OUT / f'{name}.tex').relative_to(ROOT)}")
        built.append(name)
    if skipped:
        print(f"\nnot rebuilt: {', '.join(skipped)} -- the previous .tex, if "
              f"any, is unchanged")
    return 0 if built else 1


if __name__ == "__main__":
    sys.exit(main())
